### ISSUE TITLE
Octoprint web ui can't load if hue bridge is unreachable

### ISSUE THREAD

**Issue by Salamafet** [Salamafet/ophom#14]
Add short timeout or modify the fetch process for not blocking

**Comment by cstueckrath** [comment]
same if the bridge-IP changes. A timeout wouldn't help here.
Make the config reachable from the Octoprint interface so you can at least modify or retry a pairing.
Any ETA on this?

**Comment by Salamafet** [comment]
I have not working on this issue since it was created.

I'm starting working on this right now.

**Comment by cstueckrath** [comment]
thank you very much!
Uninstalling/reinstalling with 'pip uninstall ophom' doesn't clear the config, so I'm at a dead end right now.
Could you tell me what file to edit to change the IP? I'm using octopi btw.

**Comment by Salamafet** [comment]
You can edit the _config.yaml_ file of octoprint present in `~/.octoprint`.

In _plugin_ section you can find the ophom configuration:
``` yaml
ophom:
    auto_connect: true
    auto_off: true
    auto_off_bed_temp: '50'
    auto_off_nozzle_temp: '50'
    hue_ip: 192.168.10.102
    hue_token: ********************************
    light_id: '6'
    security_connection_lost: true
```
