### ISSUE TITLE
New install is unable to find bridge

### ISSUE THREAD

**Issue by James-Coyne** [Salamafet/ophom#34]
I've installed the plugin to my octoprint instance running on a Pi 4 and it won't find my bridge. All other apps on my network are able to detect the bridge and connect to it. Is there a way to manually enter the IP of the bridge, or some way of determining why it can't find it?

![image](https://user-images.githubusercontent.com/3893276/102809109-6f341280-438f-11eb-9506-e515e5837923.png)
![image](https://user-images.githubusercontent.com/3893276/102809374-e23d8900-438f-11eb-94ae-ea5a6d9b9364.png)

**Comment by Salamafet** [comment]
When you try to add your bridge, Ophom start to reach this address https://discovery.meethue.com/
Normally there should be no problem if your bridge as the same WAN IP address as your raspberry.

If you want to manually enter the address IP you need to edit the config.yaml file of Octoprint.
Default file location: `~/.octoprint/config.yaml`

Here an part of my config file:
``` yaml
plugins:
    ophom:
        auto_connect: true
        auto_connect_time: '10'
        hue_ip: 192.168.1.5
        hue_token: -wPLFs**********************VwCaom-i
        light_id: '1'
```

If you enter only the IP address of your bridge, Ophom ask you for the pairing.
